### ISSUE TITLE
Course descriptions need to be updated

### ISSUE THREAD

**Issue by kazemicode** [kazemicode/suhi#19]
- [x] Ancient World History is no longer a course - please remove it.
- [ ] For each category (english, math, etc), is it possible to list the courses by grade level and then alpha?
- [x] For each category, can all the courses be listed on one page rather than having to scroll through multiple pages?
- [x] AP Calc AB/BC should be for 11th and 12th only
- [x] Financial Alg should be 12th only
- [x] Math 12 Fund - please add grade level 12
- [x] Biology should be 10 to 12th grade
- [x] Spanish 1/2 - please add to 12th grade
- [x] add Filipino 5/6 and Filipino American History
- [x] add Art Beginning
- [x] add Marching Band to electives
- [x] Add Intro to Design - VAPA - F (no course description), 9TH - 12TH
- [x] Add Folklorico advanced - VAPA - F (course description is in course listing)
- [x] AP Micro/Marco and Economics - list under social science for students to choose, not "G"
- [x] Band Wind is "F"
- [x] Earth Science - list under  science for students to choose, not "G"
- [x] AVID 10 is missing "elective" label
- [x] "G" distinction is missing for sociology, psychology, social issues and film, all PLTW courses, both SWC Psych courses
- [x] Please label these courses as semester courses:
  - [x] Sociology
  - [x] Psychology
  - [x] Social issues in film
  - [x] Filipino American History
  - [x] Mexican American Studies
  - [x] World Religions
  - [x] SWC Admin of Justice
  - [x] Comprehensive Health
- [x] Please check course descriptions for the two SWC Psych courses
- [x] For PE, only list PE HS CRS I, PE HSC II, PE HSC CRS II Dance -- all other PE courses, list under grad electives
- [x] SWC Admin of Justice.  list under "G" elective, no social science
- [ ] Please place all electives (grad electives and "G" electives on one page, one category).
- [x] On PE page, can we add the following description next to "PE requirement met": PE requirement is met with passing grades in 9th and 10th grade PE, along with passing the PE Fitness Test.

**Comment by kazemicode** [comment]
Keeping PLTW as "D" and AP Micro/Macro as "G" per articulation: https://hs-articulation.ucop.edu/agcourselist/institution/2002

**Comment by kazemicode** [comment]
Earth Science is also "G" per articulation: https://hs-articulation.ucop.edu/agcourselist/institution/2002

**Comment by kazemicode** [comment]
Comprehensive Health is not "A-G" per articulation https://hs-articulation.ucop.edu/agcourselist/institution/2002

**Comment by kazemicode** [comment]
Folklorico advanced was already in the catalog

**Comment by kazemicode** [comment]
Saving this: _On PE page, can we add the following description next to "PE requirement met": PE requirement is met with passing grades in 9th and 10th grade PE, along with passing the PE Fitness Test._

For the weekend since it requires going into the source code of the Course Selection Wizard.

**Comment by kazemicode** [comment]
Need clarification on this _"Please place all electives (grad electives and "G" electives on one page, one category)."_

**Are grad electives any A-G course?**

**Comment by kazemicode** [comment]
**_For each category (english, math, etc), is it possible to list the courses by grade level and then alpha?_** Not at present because of the way grade level is represented. 

Since this feature is more of a "nice to have", I can look into this after this year's rounds of preregistrations.

**Comment by LovelyLysa** [comment]
> Need clarification on this _"Please place all electives (grad electives and "G" electives on one page, one category)."_
> 
> **Are grad electives any A-G course?**
> 
> And do you mean on this page? http://kazemicode.org/suhi/a-g/g

We'd like all these courses on one "elective" page when it comes to the course selection form, rather than having a separate "G" elective and grad elective page to choose from. Perhaps on this page, students can choose their 1st, 2nd, and 3rd choice.
https://drive.google.com/file/d/1zWyxU48MCAepFk5VZo-t7ZlHVQCwcCTg/view?usp=sharing
